import type {Exercise,TrainingTemplate} from './types';
import chestBSource from './klatka_b_plan.json';
const ex=(id:string,namePl:string,nameEn:string,muscles:Exercise['muscles'],equipment:string,tip?:string,alternatives:string[]=[]):Exercise=>({id,namePl,nameEn,muscles,equipment,tip:tip||'Kontroluj fazę opuszczania i dobierz ciężar pozwalający utrzymać pełny, bezbolesny zakres.',alternatives,illustrationStart:`/exercise-art/${id}-start.webp`,illustrationEnd:`/exercise-art/${id}-end.webp`,steps:['Ustaw stabilną pozycję i napnij brzuch.','Rozpocznij ruch z kontrolowanym napięciem mięśni docelowych.','Wykonaj pełny, bezbolesny zakres bez szarpania.','Wróć wolniej do pozycji początkowej i zachowaj napięcie.'],errors:['Zbyt duży ciężar i skrócony zakres ruchu','Szarpanie ciężarem lub utrata stabilnej pozycji','Ignorowanie bólu stawowego']});
const chestBExercises:Exercise[]=chestBSource.plan.exercises.map(item=>({id:item.id,namePl:item.namePl,nameEn:item.nameEn,muscles:['Klatka'],equipment:item.equipment.join(', '),steps:item.instructions,errors:item.commonMistakes,tip:item.coachCues[0],coachCues:item.coachCues,imageUrl:item.imageUrl,sets:item.sets,repRange:item.repRange,targetRir:item.targetRir,restSeconds:item.restSeconds,tempo:item.tempo,category:item.category,primaryMuscles:item.primaryMuscles,secondaryMuscles:item.secondaryMuscles}));
export const exercises:Exercise[]=[
 ex('bench','Wyciskanie sztangi leżąc','Barbell Bench Press',['Klatka','Ramiona'],'Sztanga, ławka'),
 ex('incline-db','Wyciskanie hantli na skosie','Incline Dumbbell Press',['Klatka','Barki'],'Hantle, ławka'),
 ex('cable-fly','Rozpiętki na bramie','Cable Fly',['Klatka'],'Brama'),
 ex('chest-press','Wyciskanie na maszynie','Machine Chest Press',['Klatka','Ramiona'],'Maszyna'),
 ex('low-high','Rozpiętki z dołu','Low-to-High Cable Fly',['Klatka'],'Brama'),
 ex('pec-deck','Butterfly','Pec Deck Fly',['Klatka'],'Maszyna'),
 ex('pushup','Pompki','Push-Up',['Klatka','Ramiona'],'Masa ciała'),
 ex('arnold','Wyciskanie Arnolda','Arnold Press',['Barki'],'Hantle'),
 ex('seated-lateral','Wznosy bokiem siedząc','Seated Dumbbell Lateral Raise',['Barki'],'Hantle'),
 ex('rear-delt','Jednorącz odwodzenie na tył barku','One-Arm Cable Rear Delt Fly',['Barki'],'Brama'),
 ex('front-raise','Jednorącz wznos linki przodem','Single-Arm Cable Front Raise',['Barki'],'Brama','Prowadź rękę lekko po skosie na zewnątrz, aby lepiej poczuć przedni akton barku'),
 ex('machine-lateral','Wznosy bokiem na maszynie','Machine Lateral Raise',['Barki'],'Maszyna'),
 ex('lateral-finisher','Finisher wznosów bokiem','Lateral Raise Finisher',['Barki'],'Hantle'),
 ex('db-shoulder-press','Wyciskanie hantli siedząc','Seated Dumbbell Shoulder Press',['Barki','Ramiona'],'Hantle, ławka'),
 ex('machine-shoulder-press','Wyciskanie barkowe na maszynie','Machine Shoulder Press',['Barki','Ramiona'],'Maszyna'),
 ex('db-lateral','Wznosy hantli bokiem','Dumbbell Lateral Raise',['Barki'],'Hantle',undefined,['cable-lateral','machine-lateral']),
 ex('reverse-pec','Odwrotne rozpiętki na maszynie','Reverse Pec Deck',['Barki','Plecy'],'Maszyna',undefined,['rear-delt']),
 ex('cable-lateral','Wznosy bokiem na wyciągu','Cable Lateral Raise',['Barki'],'Brama',undefined,['machine-lateral','db-lateral']),
 ex('neutral-pulldown','Ściąganie drążka chwytem neutralnym','Neutral-Grip Lat Pulldown',['Plecy'],'Wyciąg górny'),
 ex('onearm-pulldown','Ściąganie wyciągu jednorącz','One-Arm Lat Pulldown',['Plecy'],'Wyciąg górny'),
 ex('seated-row','Wiosłowanie siedząc na wyciągu','Seated Cable Row',['Plecy','Ramiona'],'Wyciąg dolny'),
 ex('straightarm','Ściąganie prostych ramion','Straight-Arm Pulldown',['Plecy'],'Brama'),
 ex('face-pull','Przyciąganie liny do twarzy','Face Pull',['Plecy','Barki'],'Brama',undefined,['rear-delt']),
 ex('hammer-row','Wiosłowanie Hammer Strength jednorącz','One-Arm Hammer Strength Row',['Plecy','Ramiona'],'Maszyna Hammer Strength'),
 ex('wide-pulldown','Ściąganie drążka szerokim chwytem','Wide-Grip Pulldown',['Plecy'],'Wyciąg górny'),
 ex('shrugs','Szrugsy','Shrugs',['Plecy'],'Hantle lub sztanga'),
 ex('back-extension','Prostowanie grzbietu','Back Extension',['Plecy','Nogi'],'Ławka rzymska'),
 ex('incline-curl','Uginanie hantli na ławce skośnej','Incline Dumbbell Curl',['Ramiona'],'Hantle, ławka'),
 ex('cable-curl','Uginanie ramion na wyciągu','Cable Curl',['Ramiona'],'Wyciąg'),
 ex('hammer-curl','Uginanie młotkowe','Hammer Curl',['Ramiona'],'Hantle'),
 ex('rope-pushdown','Prostowanie ramion z liną','Rope Pushdown',['Ramiona'],'Wyciąg'),
 ex('overhead-triceps','Wyprost tricepsa nad głową','Overhead Cable Triceps Extension',['Ramiona'],'Wyciąg'),
 ex('arm-finisher','Finisher ramion','Arm Finisher',['Ramiona'],'Hantle lub wyciąg'),
 ex('walk','Spacer','Walk',['Regeneracja'],'Bez sprzętu'),
 ex('shoulder-mobility','Lekka mobilizacja obręczy barkowej','Light Shoulder-Girdle Mobility',['Regeneracja','Barki'],'Guma opcjonalnie'),
 ex('stretching','Łagodne rozciąganie','Gentle Stretching',['Regeneracja'],'Mata'),
 ex('sleep-hydration','Sen i nawodnienie','Sleep and Hydration',['Regeneracja'],'Bez sprzętu'),
 ...chestBExercises
];
export const templates:TrainingTemplate[]=[
 {id:'chest-a',name:'KLATKA A',focus:'Klatka',variant:'A',description:'Ciężka · progresja siłowa',exerciseIds:['bench','incline-db','cable-fly']},
 {id:chestBSource.plan.id,name:chestBSource.plan.name,nameEn:chestBSource.plan.nameEn,focus:'Klatka',variant:'B',description:chestBSource.plan.goal,goal:chestBSource.plan.goal,notes:chestBSource.plan.notes,estimatedDurationMin:chestBSource.plan.estimatedDurationMin,sourceSchemaVersion:chestBSource.schemaVersion,exerciseIds:chestBSource.plan.exercises.sort((a,b)=>a.order-b.order).map(item=>item.id)},
 {id:'chest-c',name:'KLATKA C',focus:'Klatka',variant:'C',description:'Góra klatki · izolacja',exerciseIds:['incline-db','low-high','pec-deck']},
 {id:'chest-d',name:'KLATKA D',focus:'Klatka',variant:'D',description:'Pompa · dopalenie · intensyfikacja',exerciseIds:['chest-press','pec-deck','pushup']},
 {id:'shoulders-a',name:'BARKI A',focus:'Barki',variant:'A',description:'Ciężar i masa',exerciseIds:['db-shoulder-press','machine-shoulder-press','db-lateral','reverse-pec','cable-lateral'],optionalIds:['lateral-finisher']},
 {id:'shoulders-b',name:'BARKI B',focus:'Barki',variant:'B',description:'Objętość i kompletna praca wszystkich aktonów',exerciseIds:['arnold','seated-lateral','rear-delt','front-raise','machine-lateral','lateral-finisher']},
 {id:'back-a',name:'PLECY A',focus:'Plecy',variant:'A',description:'Szerokość grzbietu',exerciseIds:['neutral-pulldown','onearm-pulldown','seated-row','straightarm','face-pull']},
 {id:'back-b',name:'PLECY B',focus:'Plecy',variant:'B',description:'Grubość grzbietu bez nacisku na klatkę',exerciseIds:['hammer-row','seated-row','wide-pulldown','straightarm','shrugs'],optionalIds:['back-extension']},
 {id:'arms-a',name:'RAMIONA A',focus:'Ramiona',variant:'A',description:'Biceps i triceps',exerciseIds:['incline-curl','cable-curl','hammer-curl','rope-pushdown','overhead-triceps'],optionalIds:['arm-finisher']},
 {id:'recovery',name:'REGENERACJA',focus:'Regeneracja',description:'Ruch lekki, mobilizacja, sen i nawodnienie',exerciseIds:['walk','shoulder-mobility','stretching','sleep-hydration']}
];
