import type{Muscle,Recovery,TrainingSession,TrainingTemplate}from'./types';import{templates}from'./data';
export const volume=(s:TrainingSession)=>s.exercises.flatMap(e=>e.sets).filter(x=>x.done&&x.kind==='working').reduce((a,x)=>a+(x.weight||0)*(x.reps||0),0);
const completedFull=(s:TrainingSession)=>!!s.completedAt&&(s.status??'full')==='full';
export const nextChestVariant=(sessions:TrainingSession[])=>{const order=['A','B','C','D'];const last=[...sessions].filter(s=>s.focus==='Klatka'&&s.variant&&completedFull(s)).sort((a,b)=>b.startedAt.localeCompare(a.startedAt))[0];return order[(last?order.indexOf(last.variant!)+1:0)%4]};
export const daysSince=(iso?:string,now=new Date())=>iso==null?null:Math.max(0,Math.floor((now.getTime()-new Date(iso).getTime())/86400000));
export const lastForMuscle=(sessions:TrainingSession[],focus:Muscle)=>[...sessions].filter(s=>s.focus===focus&&s.completedAt).sort((a,b)=>b.startedAt.localeCompare(a.startedAt))[0];
const nextVariantTemplate=(focus:Muscle,sessions:TrainingSession[])=>{const variants=templates.filter(t=>t.focus===focus);const last=lastForMuscle(sessions,focus);const i=last?.variant?variants.findIndex(t=>t.variant===last.variant):-1;return variants[(i+1)%variants.length]};
export interface Recommendation{template:TrainingTemplate;reason:string;lastTraining:string;elapsed:string;recoveryState:string;nextChest:string}
export const recommend=(sessions:TrainingSession[],r?:Recovery,now=new Date()):Recommendation=>{
 const sorted=[...sessions].filter(s=>s.completedAt).sort((a,b)=>b.startedAt.localeCompare(a.startedAt));const last=sorted[0];const nextChest=templates.find(t=>t.focus==='Klatka'&&t.variant===nextChestVariant(sessions))!;const chestLast=lastForMuscle(sessions,'Klatka');const chestDays=daysSince(chestLast?.completedAt||chestLast?.startedAt,now);const chestReady=(chestDays==null||chestDays>=2)&&(r?.chestSoreness??0)<=6;const lowReadiness=!!r&&((r.jointPain??0)>4||r.energy<=2||r.sleep<=2);let choice:TrainingTemplate;let reason:string;
 if(lowReadiness){choice=templates.find(t=>t.id==='recovery')!;reason=(r!.jointPain>4?'Ból stawów przekracza 4/10. ':'Sen lub energia są niskie. ')+'Dziś priorytetem jest odzyskanie gotowości, nie nadrabianie objętości.'}
 else if(chestReady&&last?.focus!=='Klatka'){choice=nextChest;reason=`Klatka jest gotowa, a pomiędzy pełnymi jednostkami była przerwa. Kontynuuj rotację od ${nextChest.name}.`}
 else if(last?.focus==='Klatka'){
   const light=(last.status==='light'||last.status==='incomplete');
   if(last.variant==='A'&&!light){choice=(r?.backSoreness??0)<=5?templates.find(t=>t.id==='back-a')!:templates.find(t=>t.id==='arms-a')!;reason='Ostatnio wykonano ciężką KLATKĘ A. Odsuwamy ciężkie BARKI A, aby ograniczyć przeciążenie przedniego aktonu i stawów.'}
   else if(light&&(r?.shoulderSoreness??0)<=4){choice=templates.find(t=>t.id==='shoulders-b')!;reason='Ostatni trening klatki był lekki lub nieukończony. Barki nie są mocno obolałe, więc właściwa jest objętościowa jednostka BARKI B.'}
   else{choice=(r?.backSoreness??0)<=5?nextVariantTemplate('Plecy',sessions):templates.find(t=>t.id==='arms-a')!;reason='Klatka potrzebuje przerwy przed kolejnym pełnym etapem rotacji. Wstawiamy inną partię.'}
 }else{const order:Muscle[]=['Barki','Plecy','Ramiona'];const eligible=order.filter(m=>last?.focus!==m&&!(m==='Barki'&&(r?.shoulderSoreness??0)>5)&&!(m==='Plecy'&&(r?.backSoreness??0)>6));choice=nextVariantTemplate(eligible[0]||'Ramiona',sessions);reason='Klatka zachowuje najwyższy priorytet, ale regeneruje się między pełnymi jednostkami. Wybrano najdawniej nieobciążaną dostępną partię.'}
 const lastSame=lastForMuscle(sessions,choice.focus);const elapsedDays=daysSince(lastSame?.completedAt||lastSame?.startedAt,now);const recoveryState=r?`Sen ${r.sleep}/5 · energia ${r.energy}/5 · klatka ${r.chestSoreness}/10 · barki ${r.shoulderSoreness}/10 · plecy ${r.backSoreness??0}/10 · stawy ${r.jointPain}/10`:'Brak dzisiejszej oceny — rekomendacja ostrożna.';
 return{template:choice,reason,lastTraining:lastSame?`${lastSame.name} · ${lastSame.status==='light'?'lekki':lastSame.status==='incomplete'?'nieukończony':'pełny'}`:'Brak wcześniejszego treningu tej partii',elapsed:elapsedDays==null?'pierwsza jednostka':elapsedDays===0?'dzisiaj':elapsedDays===1?'wczoraj':`${elapsedDays} dni temu`,recoveryState,nextChest:nextChest.name};
};
export const targetFor=(previous?:{weight:number|null,reps:number|null,rir:number|null})=>previous?.weight?{weight:previous.weight,reps:(previous.reps||8)+1,rir:previous.rir??2}:{weight:null,reps:10,rir:2};
